name: e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  dio:
  eva_icons_flutter: ^3.0.2
  percent_indicator:
  timeago:
  dotted_border:
  google_fonts: 2.1.1
  empty_widget: 
  intl_phone_field:
  form_field_validator:
  auth_buttons:
  badges:
  bottom_navy_bar:
  footer: 
  colorize_text_avatar:
  skeletons:
  cached_network_image:
  pin_code_fields:
  card_swiper:
  font_awesome_flutter:
  flutter_staggered_grid_view: 
  random_avatar: 
  flutter_rating_bar:
  readmore: 
  segment_control: 

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images
